--INSERT INTO game (id, game_name, game_likes_number, game_players_number) VALUES
--(1, 'Worduess', 0, 0),
--(2, 'Sudoku', 0, 0),
--(3, 'Twins-Hunt', 0, 0),
--(4, '2048', 0, 0),
--(5, 'Minesweeper', 0, 0),
--(6, 'Snake', 0, 0);